## Data encoding

## 1. Nominal encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [5]:
## create a single dataframe

df = pd.DataFrame({
    'color':['red','blue','yellow','green','green','blue','red']

})

In [6]:
df.head()

    color
0     red
1    blue
2  yellow
3   green
4   green

In [7]:
## create an instacne of onehotencoder

encoder = OneHotEncoder()

In [12]:
##perform fit and transfrom

encoded =encoder.fit_transform(df[['color']]).toarray()

In [15]:
import pandas as pd
encoded_df = pd.DataFrame(encoded, columns= encoder.get_feature_names_out())

In [16]:
encoded_df

   color_blue  color_green  color_red  color_yellow
0         0.0          0.0        1.0           0.0
1         1.0          0.0        0.0           0.0
2         0.0          0.0        0.0           1.0
3         0.0          1.0        0.0           0.0
4         0.0          1.0        0.0           0.0
5         1.0          0.0        0.0           0.0
6         0.0          0.0        1.0           0.0

## 2 lable encodning / ordinal encoding

In [17]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [18]:
lbl_encoder.fit_transform(df[['color']])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 3, 1, 1, 0, 2])

In [21]:
lbl_encoder.transform([['red']])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [22]:
### ordinal encoding

from sklearn.preprocessing import OrdinalEncoder