## Handling imbalanced dataset

1.up Sampling
2.Down sampling

In [2]:
import pandas as pd
import numpy as np

In [4]:
np.random.seed(123)

In [5]:
## cretae a dataframe with two classes

n_samples = 1000
class_0_ration =0.9
n_class_0 = int(n_samples * class_0_ration)
n_class_1 = n_samples - n_class_0

In [7]:
n_class_0, n_class_1

(900, 100)

#### Up Sampling

In [8]:
## cteate a dataframe with imbalanced dataset

class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'features_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'features_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [11]:
df= pd.concat([class_0,class_1]).reset_index(drop=True)
df.head()

   feature_1  features_2  target
0  -1.085631    0.551302       0
1   0.997345    0.419589       0
2   0.282978    1.815652       0
3  -1.506295   -0.252750       0
4  -0.578600   -0.292004       0

In [12]:
df.tail()

     feature_1  features_2  target
995   1.376371    2.845701       1
996   2.239810    0.880077       1
997   1.131760    1.640703       1
998   2.902006    0.390305       1
999   2.697490    2.013570       1

In [14]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [15]:
## upsampling

df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [16]:
from sklearn.utils import resample

In [21]:
df_minority_upsampled=resample(df_minority, replace=True,
         n_samples=len(df_majority),
         random_state=42
        )

In [22]:
df_minority_upsampled.shape

(900, 3)

In [24]:
df_minority_upsampled.head()

     feature_1  features_2  target
951   1.125854    1.843917       1
992   2.196570    1.397425       1
914   1.932170    2.998053       1
971   2.272825    3.034197       1
960   2.870056    1.550485       1

In [26]:
df_unsampled = pd.concat([df_majority, df_minority_upsampled])

In [27]:
df_unsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### Down Sampling

In [29]:
## cteate a dataframe with imbalanced dataset


n_samples = 1000
class_0_ration =0.9
n_class_0 = int(n_samples * class_0_ration)
n_class_1 = n_samples - n_class_0


class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'features_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'features_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})


df= pd.concat([class_0,class_1]).reset_index(drop=True)

In [30]:
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64