In [9]:
import pandas as pd

orders = pd.read_csv('raw_data/olist_orders_dataset.csv')
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,02-10-2017 10:56,02-10-2017 11:07,04-10-2017 19:55,10-10-2017 21:25,18-10-2017 00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,24-07-2018 20:41,26-07-2018 03:24,26-07-2018 14:31,07-08-2018 15:27,13-08-2018 00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,08-08-2018 08:38,08-08-2018 08:55,08-08-2018 13:50,17-08-2018 18:06,04-09-2018 00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,18-11-2017 19:28,18-11-2017 19:45,22-11-2017 13:39,02-12-2017 00:28,15-12-2017 00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,13-02-2018 21:18,13-02-2018 22:20,14-02-2018 19:46,16-02-2018 18:17,26-02-2018 00:00

In [10]:
orders.shape

(99441, 8)

#### Check for missing value

In [11]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

#### cross - check nulls against order status

In [12]:
orders[orders['order_delivered_customer_date'].isnull()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [13]:
orders[(orders['order_status'] =='delivered') & (orders['order_delivered_customer_date'].isnull())]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,28-11-2017 17:44,28-11-2017 17:56,30-11-2017 18:12,NaN,18-12-2017 00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,20-06-2018 06:58,20-06-2018 07:19,25-06-2018 08:05,NaN,16-07-2018 00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,01-07-2018 17:05,01-07-2018 17:15,03-07-2018 13:57,NaN,30-07-2018 00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,01-07-2018 22:05,01-07-2018 22:15,03-07-2018 13:57,NaN,30-07-2018 00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,01-07-2018 21:14,01-07-2018 21:29,03-07-2018 09:28,NaN,24-07-2018 00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,25-05-2017 23:22,25-05-2017 23:30,NaN,NaN,23-06-2017 00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,08-06-2018 12:09,08-06-2018 12:36,12-06-2018 14:10,NaN,26-06-2018 00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,27-06-2018 16:09,27-06-2018 16:29,03-07-2018 19:26,NaN,19-07-2018 00:00

In [14]:
orders[orders['order_approved_at'].isnull()]['order_status'].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [15]:
orders[orders['order_delivered_carrier_date'].isnull()]['order_status'].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

#### check the duplicate rows

In [16]:
print(orders.duplicated().sum())
print(orders['order_id'].duplicated().sum())

0
0

#### check datatype

In [17]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

#### convert data coulmn to real dates

In [18]:
date_cols =['order_purchase_timestamp', 'order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col],format='%d-%m-%Y %H:%M')

orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

#### validate the order timeline

In [19]:
print("Approved before purchase:", (orders['order_approved_at'] < orders['order_purchase_timestamp']).sum())
print("Carrier before approved:", (orders['order_delivered_carrier_date'] < orders['order_approved_at']).sum())
print("Delivered before carrier:", (orders['order_delivered_customer_date'] < orders['order_delivered_carrier_date']).sum())
print("Delivered before purchase:", (orders['order_estimated_delivery_date'] <orders['order_delivered_customer_date']).sum())

Approved before purchase: 0
Carrier before approved: 1358
Delivered before carrier: 23
Delivered before purchase: 7827

### Investigate the surprising result

In [20]:
weird = orders[orders['order_delivered_customer_date'] < orders['order_purchase_timestamp']]
print(weird[['order_id', 'order_purchase_timestamp', 'order_delivered_customer_date']].head(10))
print(weird['order_delivered_customer_date'].isnull().sum())

Empty DataFrame
Columns: [order_id, order_purchase_timestamp, order_delivered_customer_date]
Index: []
0

In [21]:
weird = orders[orders['order_delivered_customer_date'] < orders['order_purchase_timestamp']]
print(len(weird))
print(weird[['order_id', 'order_purchase_timestamp', 'order_delivered_customer_date']].head(10))

0
Empty DataFrame
Columns: [order_id, order_purchase_timestamp, order_delivered_customer_date]
Index: []

In [22]:
len(orders[orders['order_delivered_customer_date'] < orders['order_purchase_timestamp']])

0