## IPL DATA ANALYSIS

### clean the dataset

In [1]:
#import required libarary

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
##load the cvs file with the help of pandas

df = pd.read_csv("IPL_Dataset_2008_to_2026.csv", low_memory=False)
df

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,balls_per_over,overs,team_runs,team_balls,team_wicket,batter_runs,batter_balls,bowler_wicket,batting_partners,striker_out
0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,...,6,20,1,1,0,0,1,0,BB McCullum|SC Ganguly,0
1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,...,6,20,1,2,0,0,1,0,BB McCullum|SC Ganguly,0
2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,6,20,2,2,0,0,1,0,BB McCullum|SC Ganguly,0
3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,6,20,2,3,0,0,2,0,BB McCullum|SC Ganguly,0
4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,...,6,20,2,4,0,0,3,0,BB McCullum|SC Ganguly,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295727,1535465,2026-05-31,T20,Indian Premier League,2,Royal Challengers Bengaluru,Gujarat Titans,17,2,17.2,...,6,20,150,104,5,65,40,0,JM Sharma|V Kohli,0
295728,1535465,2026-05-31,T20,Indian Premier League,2,Royal Challengers Bengaluru,Gujarat Titans,17,3,17.3,...,6,20,150,105,5,10,13,0,JM Sharma|V Kohli,0
295729,1535465,2026-05-31,T20,Indian Premier League,2,Royal Challengers Bengaluru,Gujarat Titans,17,4,17.4,...,6,20,151,106,5,11,14,0,JM Sharma|V Kohli,0
295730,1535465,2026-05-31,T20,Indian Premier League,2,Royal Challengers Bengaluru,Gujarat Titans,17,5,17.5,...,6,20,155,107,5,69,41,0,JM Sharma|V Kohli,0
295731,1535465,2026-05-31,T20,Indian Premier League,2,Royal Challengers Bengaluru,Gujarat Titans,17,6,17.6,...,6,20,161,108,5,75,42,0,JM Sharma|V Kohli,0

In [3]:
#check how many row and column of there
df.shape

(295732, 46)

In [4]:
#chckeing the missing values

df.isnull().sum()

match_id                0
date                    0
match_type              0
event_name              0
innings                 0
batting_team            0
bowling_team            0
over                    0
ball                    0
ball_no                 0
batter                  0
bat_pos                 0
runs_batter             0
balls_faced             0
bowler                  0
valid_ball              0
runs_extras             0
runs_total              0
runs_bowler             0
runs_not_boundary       0
non_striker             0
non_striker_pos         0
umpires_call            0
player_of_match         0
match_won_by            0
win_outcome          4980
toss_winner             0
toss_decision           0
venue                   0
city                    0
day                     0
month                   0
year                    0
season                  0
gender                  0
team_type               0
balls_per_over          0
overs                   0
team_runs               0
team_balls              0
team_wicket             0
batter_runs             0
batter_balls            0
bowler_wicket           0
batting_partners        0
striker_out             0
dtype: int64

In [81]:
#one column has missing values: win_outcome has 4,980 blank rows.
df[df['win_outcome'].isnull()][['match_id', 'match_won_by', 'win_outcome']].drop_duplicates()

        match_id match_won_by win_outcome
15161     392190      Unknown         NaN
30707     419121      Unknown         NaN
57068     501265      Unknown         NaN
77794     598004      Unknown         NaN
81200     598017      Unknown         NaN
98800     729315      Unknown         NaN
113004    829741      Unknown         NaN
115353    829763      Unknown         NaN
121177    829813      Unknown         NaN
144440   1082625      Unknown         NaN
166931   1175365      Unknown         NaN
176392   1178424      Unknown         NaN
176666   1178426      Unknown         NaN
179302   1216493      Unknown         NaN
181275   1216547      Unknown         NaN
187447   1216512      Unknown         NaN
187698   1216517      Unknown         NaN
198245   1254077      Unknown         NaN
236750   1359519      Unknown         NaN
268306   1473469      Unknown         NaN
271126   1473481      Unknown         NaN
273705   1473492      Unknown         NaN
274316   1473495      Unknown         NaN
280816   1527685      Unknown         NaN
286873   1529281      Unknown         NaN

In [5]:
#
df['win_outcome'] = df['win_outcome'].fillna('No Result')

In [6]:
#checking one more time  ater fixing

df.isnull().sum()

match_id             0
date                 0
match_type           0
event_name           0
innings              0
batting_team         0
bowling_team         0
over                 0
ball                 0
ball_no              0
batter               0
bat_pos              0
runs_batter          0
balls_faced          0
bowler               0
valid_ball           0
runs_extras          0
runs_total           0
runs_bowler          0
runs_not_boundary    0
non_striker          0
non_striker_pos      0
umpires_call         0
player_of_match      0
match_won_by         0
win_outcome          0
toss_winner          0
toss_decision        0
venue                0
city                 0
day                  0
month                0
year                 0
season               0
gender               0
team_type            0
balls_per_over       0
overs                0
team_runs            0
team_balls           0
team_wicket          0
batter_runs          0
batter_balls         0
bowler_wicket        0
batting_partners     0
striker_out          0
dtype: int64

### cleaning the season names

In [7]:
## cleaing the season name because some are in the text or some yr in the integer
df['season'].unique()

array(['2007/08', '2009', '2009/10', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020/21', '2021', '2022',
       '2023', '2024', '2025', '2026'], dtype=object)

In [8]:
#check the unique year in the data
df['year'].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026])

In [9]:
df['year'].dtype

dtype('int64')

In [10]:
#cleaning the team names issue because team name is changing 
df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Chennai Super Kings', 'Kings XI Punjab', 'Rajasthan Royals',
       'Delhi Daredevils', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [11]:
## a mapping dictionary if you see the this old name replace with new name 

team_name_map={
    'Delhi Daredevils':'Delhi Capitals',
    'Kings XI Punjab':'Punjab Kings',
    'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
    'Rising Pune Supergiant':'Rising Pune Supergiants'
}

team_columns = ['batting_team', 'bowling_team', 'toss_winner', 'match_won_by']

for col in team_columns:
    df[col] = df[col].replace(team_name_map)

In [12]:
#checking the unique count again
print(df['batting_team'].unique())
print(df['toss_winner'].unique())

['Kolkata Knight Riders' 'Royal Challengers Bengaluru'
 'Chennai Super Kings' 'Punjab Kings' 'Rajasthan Royals' 'Delhi Capitals'
 'Mumbai Indians' 'Deccan Chargers' 'Kochi Tuskers Kerala' 'Pune Warriors'
 'Sunrisers Hyderabad' 'Rising Pune Supergiants' 'Gujarat Lions'
 'Lucknow Super Giants' 'Gujarat Titans']
['Royal Challengers Bengaluru' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Punjab Kings' 'Kolkata Knight Riders'
 'Delhi Capitals' 'Kochi Tuskers Kerala' 'Pune Warriors'
 'Sunrisers Hyderabad' 'Gujarat Lions' 'Rising Pune Supergiants'
 'Gujarat Titans' 'Lucknow Super Giants']

### Cleaning the date columns

In [13]:
df['date']=pd.to_datetime(df['date'], dayfirst=True)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_17744\1525395324.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['date']=pd.to_datetime(df['date'], dayfirst=True)

In [14]:
#checking the date type
df['date'].dtype

dtype('<M8[ns]')

In [15]:
#print top 5 date 
df['date'].head()

0   2008-04-18
1   2008-04-18
2   2008-04-18
3   2008-04-18
4   2008-04-18
Name: date, dtype: datetime64[ns]

### Checking city and venue for inconsistencies

In [16]:
## fix city

df['city'] = df['city'].replace({'Bangalore': 'Bengaluru'})

df.loc[df['city']=='Unknown', 'city'] = df.loc[df['city']=='Unknown', 'venue'].map({
    'Sharjah Cricket Stadium': 'Sharjah',
    'Dubai International Cricket Stadium': 'Dubai'
})

In [17]:
# Fix venue - collapse duplicate/inconsistent names into one per real stadium
venue_map = {
    'Arun Jaitley Stadium, Delhi': 'Arun Jaitley Stadium',
    'Barsapara Cricket Stadium, Guwahati': 'Barsapara Cricket Stadium',
    'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
    'Brabourne Stadium, Mumbai': 'Brabourne Stadium',
    'Dr DY Patil Sports Academy, Mumbai': 'Dr DY Patil Sports Academy',
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam': 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
    'Eden Gardens, Kolkata': 'Eden Gardens',
    'Feroz Shah Kotla': 'Arun Jaitley Stadium',
    'Himachal Pradesh Cricket Association Stadium, Dharamsala': 'Himachal Pradesh Cricket Association Stadium',
    'M Chinnaswamy Stadium, Bengaluru': 'M Chinnaswamy Stadium',
    'M.Chinnaswamy Stadium': 'M Chinnaswamy Stadium',
    'MA Chidambaram Stadium, Chepauk': 'MA Chidambaram Stadium',
    'MA Chidambaram Stadium, Chepauk, Chennai': 'MA Chidambaram Stadium',
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur': 'Maharaja Yadavindra Singh International Cricket Stadium',
    'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh': 'Maharaja Yadavindra Singh International Cricket Stadium',
    'Maharashtra Cricket Association Stadium, Pune': 'Maharashtra Cricket Association Stadium',
    'Punjab Cricket Association IS Bindra Stadium, Mohali': 'Punjab Cricket Association Stadium, Mohali',
    'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh': 'Punjab Cricket Association Stadium, Mohali',
    'Punjab Cricket Association IS Bindra Stadium': 'Punjab Cricket Association Stadium, Mohali',
    'Rajiv Gandhi International Stadium, Uppal': 'Rajiv Gandhi International Stadium',
    'Rajiv Gandhi International Stadium, Uppal, Hyderabad': 'Rajiv Gandhi International Stadium',
    'Sardar Patel Stadium, Motera': 'Narendra Modi Stadium, Ahmedabad',
    'Sawai Mansingh Stadium, Jaipur': 'Sawai Mansingh Stadium',
    'Shaheed Veer Narayan Singh International Stadium, Raipur': 'Shaheed Veer Narayan Singh International Stadium',
    'Wankhede Stadium, Mumbai': 'Wankhede Stadium',
    'Zayed Cricket Stadium, Abu Dhabi': 'Sheikh Zayed Stadium',
}

In [18]:
df['venue'] = df['venue'].replace(venue_map)

In [19]:
df['city'].nunique()

36

In [20]:
df['venue'].nunique()

37

In [21]:
#save the clean file

df.to_csv('cleaned_ipl_data.csv', index=False)


**Recape what we learn**

**Issue 1**	                                             
win_outcome missing values   
**What you learned**
Missing doesn't always mean broken — investigate why before filling
**Issue 2**	 
season mixed format	
**What you learned**
Not everything needs fixing — sometimes you just need to understand it
**Issue 3**	 
Team name inconsistencies	
**What you learned**
Same real-world entity, different labels across time — needed a mapping dictionary, applied to every relevant column
**Issue 4**	
date as text	
**What you learned**
Wrong data type silently breaks sorting/filtering — always convert dates explicitly with the right format
**Issue 5**	
city/venue messiness
**What you learned**
Real-world data sources are inconsistent — same stadium can appear 3+ different ways